### ISSUE TITLE
`xhr poll error` report from user

### ISSUE THREAD

**Issue by simonwheatley** [Automattic/vip-cli#323] opened 2019-04-29 13:03 UTC
A user reports the following error when they try to run a paged post list command:

```
vip --app=774 --env=preprod -- wp post list --post_type=pmc_list_item --posts_per_page=10 --paged=2
```

![Screenshot 2019-04-29 at 5 22 04 PM](https://user-images.githubusercontent.com/233434/56958419-2daf7d80-6b42-11e9-8ae2-5a58ea6b5584.png)

I'm enquiring whether it works without `--paged` and whether they can run other commands. Ping me in Slack for the ticket number 🙂

**Comment by simonwheatley** [comment] 2019-04-30 11:28
Added image of error output @nickdaugherty 

User can no longer replicate, possibly due to https://github.com/Automattic/vip-go-api/issues/1906

**Comment by dchymko** [comment] 2019-06-04 18:44
Closing this as a "cannot reproduce."
Also important to note that with the upgrade to 5.2 we get a "Site is experiencing technical difficulties" instead of a Fatal or empty response:
```
vip --app=774 --env=preprod -- wp post list --post_type=pmc_list_item --posts_per_page=10 
Error: The site is experiencing technical difficulties.
```

**Closed as completed** 2019-06-04 18:44 UTC
Labels: [Type] Bug
