### ISSUE TITLE
Cannot sandbox sites

### ISSUE THREAD

**Issue by simonwheatley** [Automattic/vip-cli#97] opened 2016-12-20 15:15 UTC
When I try to sandbox a site I get an error:

```
$ vip sandbox start 68
Warning: There are more than 5 total sandbox containers on this host. Consider deleting some unused ones with `vip sandbox delete <site>`
Waiting for sandbox to start...
{ [Error: ENOENT: no such file or directory, open '/home/vipdev/.vip-cli/sbox']
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '/home/vipdev/.vip-cli/sbox' }
```

I can see the sandbox running when I run `vip sandbox list`.

**Comment by mjangda** [comment] 2016-12-20 15:51
Dupe of #95. Potential fix in #96.

**Closed by mjangda** 2016-12-20 15:51 UTC
