### ISSUE TITLE
Check and suggest innodb-buffer increase post SQL import

### ISSUE THREAD

**Issue by david-binda** [Automattic/vip-cli#273] opened 2017-12-12 18:30 UTC
It would be awesome if the `vip import db` command, once it finishes, checked the innodb-pool's size and eventually prompted the user to request an increase if needed.

**Comment by joshbetz** [comment] 2017-12-12 18:35
This is actually a dupe of #239

**Closed by joshbetz** 2017-12-12 18:35 UTC
Labels: enhancement, feature/imports

**Comment by david-binda** [comment] 2017-12-12 18:37
Sorry and thanks for sorting this out. Consider this being a +1 on the original issue :)
