### ISSUE TITLE
Authentication flow breaks on Debian Linux

### ISSUE THREAD

**Issue by simonwheatley** [Automattic/vip-cli#336] opened 2019-05-01 10:02 UTC
From @gudmdharalds:

I've been testing this and had cannot go past this:

```
$ vip

  Welcome to
   _    __________     ______
  | |  / /  _/ __ \   / ____/___
  | | / // // /_/ /  / / __/ __ \
  | |/ // // ____/  / /_/ / /_/ /
  |___/___/_/       \____/\____/

  VIP CLI is your tool for interacting with and managing your VIP Go applications.

  To get started, we need an access token for your VIP account. We'll open https://dashboard.wpvip.com/me/cli/token in your web browser; follow the instructions there to continue.
```

It just freezes here. Is there a way to bypass this and just enter the token manually?

OS is `Linux 4.19.0-1-amd64 #1 SMP Debian 4.19.12-1 (2018-12-22) x86_64 GNU/Linux`

```
$ vip -v
1.4.1
```

**Comment by dchymko** [comment] 2019-05-01 16:40
Tried to reproduce using a Docker Debian image and was unable to reproduce. I.e.  (`✔ Ready? (y/N) ` prompt displays correctly)

Docker version:
`Linux 621815107beb 5.0.0-13-generic #14-Ubuntu SMP Mon Apr 15 14:59:14 UTC 2019 x86_64 GNU/Linux`

Steps to test:
```
docker run -it debian /bin/bash
apt-get update
apt-get install curl git python
adduser nodetest   #  (doesn't matter what you set for the password, etc)
su nodetest
curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.34.0/install.sh | bash
exit
su nodetest    # (to re-run shell with nvm loaded)
nvm install 10
npm install -g @automattic/vip  #(Note, you will see an install "error" here, but the next command will work)
vip
```

Note the cli has worked correctly for me on Ubuntu 18.04/19.04 so maybe its something to do with a specific node or Debian version.

**Comment by mjangda** [comment] 2019-06-06 22:12
Closing; we can revisit if we get more reports or details.

**Closed as completed by mjangda** 2019-06-06 22:12 UTC
Labels: [Type] Bug
