### ISSUE TITLE
Handle failed API response in `db buffer-pool`

### ISSUE THREAD

**Issue by philipjohn** [Automattic/vip-cli#249] opened 2017-09-09 14:19 UTC
It looks like the API is failing to respond as expected and the command doesn't handle that well:

```
vip db buffer-pool [ID]
-- Site: [ID]
-- Domain: [example]-develop.go-vip.co
-- Environment: develop
-- Growth Factor: 0.75
+---------+----------+----------+--------------------+--------------+
| data_mb | index_mb | total_mb | mariadb_current_mb | suggested_mb |
+---------+----------+----------+--------------------+--------------+
|     641 |      171 |      811 |               2048 |          609 |
+---------+----------+----------+--------------------+--------------+
/home/vipdev/.node/lib/node_modules/wpvip-cli/build/bin/vip-db.js:102
				if (err.response.statusCode === 404) {
				       ^

TypeError: Cannot read property 'response' of null
    at /home/vipdev/.node/lib/node_modules/wpvip-cli/build/bin/vip-db.js:102:12
    at Request.callback (/home/vipdev/.node/lib/node_modules/wpvip-cli/node_modules/vip/node_modules/superagent/lib/node/index.js:785:12)
    at Request.request.callback (/home/vipdev/.node/lib/node_modules/wpvip-cli/build/lib/api.js:41:12)
    at IncomingMessage.<anonymous> (/home/vipdev/.node/lib/node_modules/wpvip-cli/node_modules/vip/node_modules/superagent/lib/node/index.js:990:12)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)
```

The configured buffer pool size is missing from the output, so I'm assuming that's the API request that failed.

**Comment by joshbetz** [comment] 2017-09-09 15:14
Dupe of #242

**Closed by joshbetz** 2017-09-09 15:14 UTC
